server:
  port: ${PORT:8040}

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/Kaiyuanliu/spring-cloud-demo/
          uri: file:/Users/apple/github/spring-cloud-demo
          search-paths: microservice-config-repo