server:
  port: ${PORT:8011}

eureka:
  instance:
    hostname: feign
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

spring:
  application:
    name: microservice-consumer-user-feign
  thymeleaf:
    enabled: false

