server:
  port: ${PORT:8011}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

spring:
  application:
    name: microservice-consumer-movie-feign
  thymeleaf:
    enabled: false

