server:
  port: ${PORT:8031}

spring:
  application:
    name: microservice-hystrix-turbine

turbine:
  aggregator:
    clusterConfig: default
  appConfig:  microservice-consumer-user-feign,microservice-consumer-user-ribbon
  clusterNameExpression: new String("default")

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka